language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

after_success:
  - test $TRAVIS_R_VERSION = "3.2.4" && Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      - libhunspell-dev

r_github_packages:
  - hadley/devtools

bioc_required: true
bioc_packages:
  - BiocInstaller

before_script:
    - git config --global user.name "travis"
    - git config --global user.email "travis@example.org"

after_success:
  - Rscript -e 'covr::codecov()'
